name: Tests
on: push
jobs:
  test:
    name: Run tests (${{ matrix.target }})
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            target: jvm
            task: check
          - os: macos-latest
            target: iosSimulatorArm64
            task: iosSimulatorArm64Test
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-java@v6
        with:
          distribution: temurin
          java-version: 21
      - uses: gradle/actions/setup-gradle@v6.3.0

      - name: ${{ matrix.task }}
        run: ./gradlew ${{ matrix.task }}
